spring:
  application:
    name: task-app
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:mysql://db:3306/task
    username: 'task_user'
    password: 'pleasechange'
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
